### ISSUE TITLE
Cartesian closed

### ISSUE THREAD

**Issue by b-mehta** [b-mehta/topos#4]
We're going to need cartesian closed categories. My intuition is to define it by asserting that the right adjoint to product exists, but maybe this is awkward to phrase using what's in mathlib - let's investigate.

**Comment by b-mehta** [comment]
It doesn't seem too bad. We might need to add that (- * X) is a functor, and then can just say `is_left_adjoint (prod X)`

**Comment by EdAyers** [comment]
93163fec907ec6daf8ffe469a366538ad17d0a5a

**Comment by b-mehta** [comment]
This seems pretty done I think. Let's make them easy to use now
